name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! 👋  Thank you for opening your first Lightkurve issue! 🙏  One of our maintainers will get back to you as soon as possible. 👩‍🚀  We love that you are using Lightkurve and appreciate your feedback. 👍'
        pr-message: 'Hi there! 👋  Thank you for opening your first Lightkurve pull request! 🙏  One of our maintainers will get back to you as soon as possible. 👩‍🚀  We love that you are using Lightkurve and appreciate your input. 👍'
